FROM craigrhodes/dcl
ENV CAML_LD_LIBRARY_PATH="/home/dcl-user/.opam/system/lib/stublibs:/usr/lib/ocaml/stublibs"
ENV MANPATH="/home/dcl-user/.opam/system/man"
ENV PERL5LIB="/home/dcl-user/.opam/system/lib/perl5"
ENV OCAML_TOPLEVEL_PATH="/home/dcl-user/.opam/system/lib/toplevel"
ENV PATH="/home/dcl-user/.opam/system/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
USER dcl-user
ENTRYPOINT ["/bin/bash"]
